### ISSUE TITLE
Code base is very less commented.

### ISSUE THREAD

**Issue by jitendra3109** [MartinoMensio/OMA-project#1]
I look your codebase of this project. 
Can please explain what is logic you are implemented?
In a language.
` 

     VehicleRoutingProblem.Builder vrpBuilder = VehicleRoutingProblem.Builder.newInstance();
    VehicleRoutingProblem vrp = vrpBuilder.build();
    final StateManager stateManager = new StateManager(vrp);
    ConstraintManager constraintManager = new ConstraintManager(vrp, stateManager);

    SolutionCostCalculator costCalculator = new SolutionCostCalculator() {
        @Override
        public double getCosts(VehicleRoutingProblemSolution solution) {
            double costs = 0.;
            for (VehicleRoute route : solution.getRoutes()) {
                costs += route.getVehicle().getType().getVehicleCostParams().fix;
                costs += stateManager.getRouteState(route, InternalStates.COSTS, Double.class);
            }
            int nRoutes = solution.getRoutes().size();
            // penalty for unused routes
            costs += (solution.getRoutes ().size () - nRoutes) * 1000000;
            // penalty for unassigned jobs
            costs += solution.getUnassignedJobs().size() * 1000000;
            int minJobsInRoute = solution.getRoutes().stream().mapToInt(route).min().getAsInt();
            int maxJobsInRoute = solution.getRoutes().stream().mapToInt(getRouteActivitiesSize).max().getAsInt();
            double jobsRate = ((double)maxJobsInRoute) / minJobsInRoute;
            // penalty for unbalanced routes
            if (MyUtil.wantBalanced && jobsRate > MyUtil.balanceFactor) {
                costs += 100000 * jobsRate;
            }
            return costs;
        }
    };
    // HARD constraint in insertion
    HardRouteConstraint routeLevelConstraint = new HardRouteConstraint() {
        private int maxJobPerTourLowN = (int)Math.floor(((double)MyUtil.nJobs) / (MyUtil.numVehiclesToUse - 1));
        private int maxJobPerTourHighN = (int)Math.ceil(((double)MyUtil.nJobs) / (MyUtil.numVehiclesToUse - 1)) + 1;

        @Override
        public boolean fulfilled(JobInsertionContext insertionContext) {
            int maxJobPerTour;
            if (MyUtil.numVehiclesToUse > 9) {
                maxJobPerTour = maxJobPerTourHighN;
            } else {
                maxJobPerTour = maxJobPerTourLowN;
            }
            if (insertionContext.getRoute().getTourActivities().getActivities().size() >= maxJobPerTour) {
                return false;
            }
            return true;
        }
    };
}``

**Comment by MartinoMensio** [comment]
hope this explains better 0f7c191
As you can see, some values have not a good reason for being there, it's simply a tuning of the parameters to reach acceptable results on the instances selected. We had no time to do a clean solutions
